hlxsites/24petwatch

- blocks/hero/hero.css
- styles/styles.css
Fix #2 
Test URLs:
- After: https://hero--24petchwatch--hlxsites.hlx.page/
> hero styling

- styles/styles.css
Fix #9 
Test URLs:
- After: https://highlight--24petchwatch--hlxsites.hlx.page/
> highlight section

- blocks/columns/columns.css
- styles/styles.css
Fix #6 
Test URLs:
- After: https://columns--24petchwatch--hlxsites.hlx.page/
> columns styling

- scripts/lib-franklin.js
- styles/styles.css
Fix #8 
Test URLs:
- After: https://buttons--24petchwatch--hlxsites.hlx.page/
> buttons styling

- styles/lazy-styles.css
- styles/styles.css
Fix #10 
Test URLs:
- After: https://hyperlinks--24petchwatch--hlxsites.hlx.page/
> hyperlinks styling

- styles/fonts.css
- styles/lazy-styles.css
- styles/styles.css
Test URLs:
- After: https://font-change--24petchwatch--hlxsites.hlx.page/
> font optimizations

- blocks/hero/hero.css
Test URLs:
- After: https://hero-revisited--24petchwatch--hlxsites.hlx.page/
> hero fixes

- blocks/cards/cards.css
- blocks/cards/cards.js
Fix #7 
Test URLs:
- After: https://cards--24petchwatch--hlxsites.hlx.page/
> cards styling

- blocks/cards/cards.js
Fix #22 
Test URLs:
- After: https://dynamic-blog-teaser--24petchwatch--hlxsites.hlx.page/
> dynamically load blog teaser

- blocks/header/header.css
- blocks/header/header.js
- styles/styles.css
Test URLs:
- After: https://navigation--24petwatch--hlxsites.hlx.page/
> header implementation

- scripts/delayed.js
Test URLs:
- After: https://gtm--24petwatch--hlxsites.hlx.page/
> add GTM via delayed

- scripts/lib-analytics.js
- scripts/lib-franklin.js
- scripts/scripts.js
Test URLs:
- After: https://betterlinktracking--24petwatch--hlxsites.hlx.page/
> prevent link clicks to be tracked twice

- blocks/footer/footer.js
- blocks/header/header.js
- scripts/delayed.js
- scripts/lib-analytics.js
- scripts/lib-franklin.js
- scripts/scripts.js
Fix #34 
This PR contains the changes to capture following events and send them to GTM:
- `main`:
- cta clicks (`cta_click` event)
- `header`:
- all clicks (`navigation` event)
- cta clicks (`cta_click` event)
- report lost and found button click (`pet_lost_found_report_click` event) 
- `footer`
- all clicks (`navigation` event)
- social interaction clicks (`social_interactions` event)
- phone number clicks (`click_to_call` event) 
Test URLs:
- After: https://custom-tracking--24petwatch--hlxsites.hlx.live/
> custom tracking for GTM

- helix-query.yaml
Test URLs:
- After: https://blog-index--24petwatch--hlxsites.hlx.page/
> Adding a blog index

- helix-query.yaml
Test URLs:
- After: https://blog-index--24petwatch--hlxsites.hlx.page/
> Blog index

- tools/importer/import.js
- tools/importer/transformers/blogArticle.js
- tools/importer/transformers/blogBanner.js
- tools/importer/transformers/cleanBlog.js
- tools/importer/transformers/index.js
- tools/importer/transformers/metadata.js
Test URLs:
- After: https://blog-import--24petwatch--hlxsites.hlx.page/
> Blog import

- helix-query.yaml
Test URLs:
- After: https://adding-author-index--24petwatch--hlxsites.hlx.page/
> Adding author and tags

- helix-query.yaml
Test URLs:
- After: https://better-blog-index--24petwatch--hlxsites.hlx.page/
> Better blog index

- helix-query.yaml
Fix #41 
Test URLs:
- After: https://fixing-canada-tags--24petwatch--hlxsites.hlx.page/
> Fixing Canada tags

- blocks/cards/cards.js
- styles/styles.css
Test URLs:
- Before: https://main--24petwatch--hlxsites.hlx.page/blog/7-creative-ways-to-keep-your-pets-memory-alive
- After: https://centering-images--24petwatch--hlxsites.hlx.page/blog/7-creative-ways-to-keep-your-pets-memory-alive
> Centering images

- helix-query.yaml
Test URLs:
- After: https://fragement-showing-up-in-blog-search--24petwatch--hlxsites.hlx.page/
> Remove fragments from query-index

- styles/styles.css
Test URLs:
- After: https://link-not-bold--24petwatch--hlxsites.hlx.page/
> Make link not bold in blog post

- blocks/cards/cards.js
Test URLs:
- Before: https://main--24petwatch--hlxsites.hlx.page/blog/diy-grow-your-own-cat-grass
- After: https://related-articles--24petwatch--hlxsites.hlx.page/blog/diy-grow-your-own-cat-grass
> Related articles

- blocks/header/header.js
Test URLs:
- After: https://fixing-usa-link--24petwatch--hlxsites.hlx.page/
> Fixing USA link

- blocks/header/header.js
Test URLs:
- After: https://header-target-blank--24petwatch--hlxsites.hlx.page/
> Remove target blank in the header to same domain

- blocks/header/header.js
Test URLs:
- After: https://updating-links-canada--24petwatch--hlxsites.hlx.page/
> Updating links in header to canada

- README.md
Diagram.
Test URLs:
- After: https://diagram--24petwatch--hlxsites.hlx.page/
> Starting a diagram

- blocks/header/header.css
- blocks/header/header.js
- tools/importer/transformers/cleanUpHTML.js
- tools/importer/transformers/header.js
Test URLs:
- After: https://import-from-crosswalk-prod--24petwatch--hlxsites.hlx.page/
> Import from prod

- blocks/header/header.css
- styles.css
- styles/styles.css
Fix Jira PM - 50
Test URLs:
- After: https://mobile-nav-crowded--24petwatch--hlxsites.hlx.page/
> PM-50: Project Crosswalk mobile nav

- scripts/scripts.js
Test URLs:
- Before: https://main--24petwatch--hlxsites.hlx.page/blog/gifts-for-the-pet-lover-in-your-life-top-10-gifts-for-pets-and-their-parents
- After: https://localhost-quick-fix--24petwatch--hlxsites.hlx.page/blog/gifts-for-the-pet-lover-in-your-life-top-10-gifts-for-pets-and-their-parents
> Rewrite localhost URLs

- blocks/header/header.js
Test URLs:
- After: https://feature-ca-externallinks--24petwatch--hlxsites.hlx.page/
> Updating External links logic

- blocks/header/header.js
Reverts hlxsites/24petwatch#68
Please always provide the [GitHub issue(s)](https://github.com/hlxsites/24petwatch/issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Test URLs:
Before: https://main--24petwatch--hlxsites.hlx.page/
After: https://revert-68-feature-ca-externallinks--24petwatch--hlxsites.hlx.page/
> Revert "Updating External links logic"

- scripts/scripts.js
Test URLs:
- After: https://blog-footer-fragment--24petwatch--hlxsites.hlx.page/
> Using a CA frgament for the CA blog page

- blocks/header/header.js
Ticket for this code change https://pethealthinc.atlassian.net/browse/PM-83
Test URLs:
- After: https://feature-pm-83-ca-navlinks--24petwatch--hlxsites.hlx.page/
> updated header.js

- tools/sidekick/config.json
Test URLs:
- After: https://<branch>--24petwatch--hlxsites.hlx.page/
> Adding AEMaaCS assets to Side Kick

- blocks/header/header.js
- blocks/overflowhero/overflowhero.css
Test URLs:
- After: https://pawpack-discounty--24petwatch--hlxsites.hlx.page/
> Creating styles for discount

- blocks/hero/hero.css
Test URLs:
- After: https://hero-red--24petwatch--hlxsites.hlx.page/
> Updating Hero CSS secundary

- blocks/accordion/accordion.css
- blocks/accordion/accordion.js
- blocks/columns/columns.css
- styles/styles.css
Test URLs:
- Before: https://www.24petwatch.com/lost-pet-protection/faq
- After: https://faq--24petwatch--hlxsites.hlx.page/drafts/iakobchu/faq
> #85 FAQ Page

- blocks/cards/cards.css
- blocks/embed/embed.js
- blocks/header/header.js
- blocks/lost-pet-poster-generator/lost-pet-poster-generator.css
- blocks/lost-pet-poster-generator/lost-pet-poster-generator.js
- scripts/lib-analytics.js
- styles/styles.css
- tools/importer/transformers/makeProxySrcs.js
Fix JS and CSS linter
Test URLs:
- Before: https://develop--24petwatch--hlxsites.hlx.page
- After: https://fix-linter--24petwatch--hlxsites.hlx.page
> Fix js linter

- blocks/lost-pet-poster-generator/lost-pet-poster-generator.js
Fix validator on click
Test URLs:
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/bkorablov/lost-pet-protection/lost-pet-poster-generator
- After: https://fix-validator--24petwatch--hlxsites.hlx.page/drafts/bkorablov/lost-pet-protection/lost-pet-poster-generator
> Fix validator on click

- blocks/cards/cards.css
Test URLs:
Before: https://main--24petwatch--hlxsites.hlx.page/about-us
After: https://fix-about-us--24petwatch--hlxsites.hlx.page/drafts/iakobchu/about-us
> #103 Fix images on about us page

- blocks/columns/columns.css
- styles/styles.css
Fix #92
Test URLs (same page used for both USA and Canada):
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/miweis/why-microchip
- After: https://92-why-microchip--24petwatch--hlxsites.hlx.page/drafts/miweis/why-microchip
> #92: Why Microchip page

- blocks/contact-us/contact-us.css
- blocks/contact-us/contact-us.js
- scripts/scripts.js
- styles/styles.css
Fix #99
Test URLs:
Before: https://www.24petwatch.com/ca/contact-us
After: https://contact-us--24petwatch--hlxsites.hlx.page/drafts/iakobchu/contact-us
> #99 Contact Us Form

- blocks/cards/cards.css
- styles/styles.css
Fix #113
Test URLs:
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/miweis/pet-recovery-tips
- After: https://113-pet-recovery-tips--24petwatch--hlxsites.hlx.page/drafts/miweis/pet-recovery-tips
**Note:** USA page is closely similar to Canadian; only the links in the Word document changed.
> #113: Pet Recovery Tips

- blocks/cards/cards.css
- blocks/columns/columns.css
- styles/styles.css
Fix #115
Test URLs:
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/miweis/membership-benefits
- After: https://115-membership-benefits--24petwatch--hlxsites.hlx.page/drafts/miweis/membership-benefits
**Note:** USA page is closely similar to Canadian; only the links in the Word document changed.
> 115 membership benefits

- blocks/accordion/accordion.css
- blocks/columns/columns.css
- blocks/hero/hero.css
- styles/styles.css
Test URLs:
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/miweis/transfer-microchip-registration
- After: https://117-transfer-microchip-registration--24petwatch--hlxsites.hlx.page/drafts/miweis/transfer-microchip-registration
**Note:** USA page is closely similar to Canadian; only some of the links in the Word document changed.
> #117: Transfer Microchip Registration

- blocks/hero/hero.css
Test URLs:
- After: https://changing-wrapping-in-hero--24petwatch--hlxsites.hlx.page/
> Fixing the wrapping

- blocks/hero/hero.css
Fix #119
Test URLs:
USA:
- Before: https://main--24petwatch--hlxsites.hlx.page/drafts/miweis/
- After: https://119-summer-2024-campaign--24petwatch--hlxsites.hlx.page/drafts/miweis/
Canada:
- Before: https://main--24petwatch--hlxsites.hlx.page/drafts/miweis/ca/
- After: https://119-summer-2024-campaign--24petwatch--hlxsites.hlx.page/drafts/miweis/ca/
> #119: Summer 2024 Campaign

- blocks/columns/columns.css
- styles/styles.css
Fix #124
Test URLs:
USA:
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/miweis/membership
- After: https://124-membership--24petwatch--hlxsites.hlx.page/drafts/miweis/membership
CA:
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/miweis/ca/membership
- After: https://124-membership--24petwatch--hlxsites.hlx.page/drafts/miweis/ca/membership
> #124: Membership page

- styles/styles.css
Fix #101
Test URLs:
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/develop/ca/underwriter
- After: https://101-icon-for-pdf-links--24petwatch--hlxsites.hlx.page/drafts/develop/ca/underwriter
> 101: Icon for PDF links

- styles/styles.css
Fix #100
Test URLs (sample):
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/miweis/underwriter
- After: https://100-icon-for-external-links--24petwatch--hlxsites.hlx.page/drafts/miweis/underwriter
> #100: Icon for external links

- styles/styles.css
Fix #128
Test URLs:
USA:
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/miweis/html-sitemap
- After: https://128-sitemap--24petwatch--hlxsites.hlx.page/drafts/miweis/html-sitemap
CA:
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/miweis/ca/html-sitemap
- After: https://128-sitemap--24petwatch--hlxsites.hlx.page/drafts/miweis/ca/html-sitemap
> #128: Sitemap

- blocks/header/header.css
- blocks/header/header.js
Fix #98
Test URLs (example):
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/develop/lost-pet-protection/faq
- After: https://98-breadcrumbs--24petwatch--hlxsites.hlx.page/drafts/develop/lost-pet-protection/faq
**Note:** Used the Block Party implementation of Breadcrumbs as a guide.
> #98: breadcrumbs: enabled

- blocks/cards/cards.css
- blocks/columns/columns.css
- scripts/scripts.js
- styles/styles.css
Fix #132
Test URLs:
Before: https://www.24petwatch.com/lost-pet-protection/fi-smart-collar
After: https://fi-smart-collar--24petwatch--hlxsites.hlx.page/drafts/iakobchu/lost-pet-protection/fi-smart-collar
> #132 fi smart collar page

- blocks/cards/cards.js
Test URLs:
Before: https://www.24petwatch.com/lost-pet-protection/fi-smart-collar
After: https://cards-without-links--24petwatch--hlxsites.hlx.page/drafts/iakobchu/lost-pet-protection/fi-smart-collar
> added a check for the static cards that does not require links

- blocks/pet-tags/pet-tags.css
- blocks/pet-tags/pet-tags.js
- styles/styles.css
Fix #132
Test URLs:
- Before: https://main--24petwatch--hlxsites.hlx.page/drafts/miweis/ca/lost-pet-protection/pet-tags/
- After: https://138-canadian-pet-tags--24petwatch--hlxsites.hlx.page/drafts/miweis/ca/lost-pet-protection/pet-tags/
> #132: Canadian Pet Tags

- blocks/contact-us/contact-us.js
- scripts/scripts.js
Test URLs:
Before: https://www.24petwatch.com/contact-us
After: https://contact-us-update--24petwatch--hlxsites.hlx.page/drafts/develop/contact-us
Updated app builder action was redeployed to:
https://348665-24petwatch-stage.adobeioruntime.net/api/v1/web/24petwatch-appbuilder/contact-form
Code:
https://git.corp.adobe.com/fdelval/petwatch-forms/commit/41396f494b26e0d3e784aa38eb2ab609138db719
Data is saved to
HelixProjects > documents > sites > 24petwatch >  contact-us-form.xlsx
> Contact us update

- blocks/header/header.css
Fix #387
Test URLs:
- After: https://pm-387-mobile-view-drop-styling--24petwatch--hlxsites.hlx.page/
> PM#387 - EDS Mega Nav - Mobile Drop Downs Styling

- blocks/header/header.css
- blocks/header/header.js
Fix #386
Test URLs:
- After: https://pm-386-mobile-country-selector--24petwatch--hlxsites.hlx.page/
> PM#386 - Mega Nav - Mobile Country Selector

- blocks/hero/hero.css
Fix #391
Test URLs:
- After: https://pm-391-homepage-overflow-text--24petwatch--hlxsites.hlx.page/
> PM#391 - 24PW: Homepage - Overflow Text

- blocks/fragment-tabs/fragment-tabs.js
Test URLs:
Before: https://www.24petwatch.com/lost-pet-protection/report-lost-found-pet
After: https://fragment-tabs-fix--24petwatch--hlxsites.hlx.page/drafts/bkorablov/lost-pet-protection/report-lost-found-pet
> fixed scope for fragment-tabs block

- blocks/columns/columns.css
- blocks/hero/hero.css
- blocks/pet-tags/pet-tags.css
- blocks/pet-tags/pet-tags.js
Fix #148
Example ... Test URLs:
- Before: https://develop--24petwatch--hlxsites.hlx.page/lost-pet-protection/
- After: https://148-prep-images--24petwatch--hlxsites.hlx.page/lost-pet-protection/
> #148: prep for production: updated CSS and JavaScript

- blocks/columns/columns.css
- blocks/columns/columns.js
Test URLs:
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/develop/pet-insurance
- After: https://pet-insurance-iframe--24petwatch--hlxsites.hlx.page/drafts/develop/pet-insurance
> Pet insurance iframe

- scripts/lib-franklin.js
Fix #146
Test URLs:
- After: https://telephone-links--24petwatch--hlxsites.hlx.page/
> #146 Update tel link behaviour

- blocks/header/header.css
- blocks/header/header.js
Test URLs:
- Before: https://main--24petwatch--hlxsites.hlx.page/lost-pet-protection/faq
- After: https://breadcrumbs-update--24petwatch--hlxsites.hlx.page/lost-pet-protection/faq
> #152 Add breadcrumbs to Mobile view

- blocks/columns/columns.css
Fix #155 
Test URLs:
- Before: https://main--24petwatch--hlxsites.hlx.page/lost-pet-protection/fi-smart-collar
- After: https://fi-smart-collar-ui-fix--24petwatch--hlxsites.hlx.page/lost-pet-protection/fi-smart-collar
> #155 Fix title issue identified by TC_24

- blocks/table/table.css
Test URLs:
- Before: https://main--24petwatch--hlxsites.hlx.page/lost-pet-protection
- After: https://pet-protection-ui-fix--24petwatch--hlxsites.hlx.page/lost-pet-protection/
> #157 Fix title issue identified by TC_06

- blocks/footer/footer.js
Test URLs:
- After: https://making-footer-work--24petwatch--hlxsites.hlx.page/
> Making footer work

- blocks/pet-tags/pet-tags.js
Fix #163
Test URLs:
- Before: https://develop--24petwatch--hlxsites.hlx.page/ca/lost-pet-protection/pet-tags
- After: https://163-canadian-pet-tag-prices--24petwatch--hlxsites.hlx.page/ca/lost-pet-protection/pet-tags
> Update Canadian pet tag prices

- blocks/contact-us/contact-us.js
Test URLs:
- After: https://prd-captcha-update--24petwatch--hlxsites.hlx.page/
> prod captcha site key added

- blocks/header/header.css
- scripts/lib-franklin.js
Test URLs:
- After: https://update-targets-for-links--24petwatch--hlxsites.hlx.page/
> #167 Open internal footer links in the same window

- blocks/contact-us/contact-us.js
- blocks/found-pet-report/found-pet-report.js
- scripts/configs.js
Test URLs:
- After: https://add-configuration-file--24petwatch--hlxsites.hlx.page/
> #169 Add configuration file for 24petwatch

- blocks/trustedsite/trustedsite.css
- blocks/trustedsite/trustedsite.js
Test URLs:
- Before: https://main--24petwatch--hlxsites.hlx.page/drafts/iakobchu/trust
- After: https://trustedsite-block--24petwatch--hlxsites.hlx.page/drafts/iakobchu/trust
> #171 Create TrustedSite block

- blocks/header/header.css
- blocks/header/header.js
Test URLs:
- Before: https://main--24petwatch--hlxsites.hlx.page/lost-pet-protection
- After: https://breadcrumbs-alignment--24petwatch--hlxsites.hlx.page/lost-pet-protection
> #173 Wrap breadcrumbs in a section

- blocks/footer-paid/footer-paid.css
- blocks/footer-paid/footer-paid.js
- blocks/header-paid/header-paid.css
- blocks/header-paid/header-paid.js
- blocks/hero/hero.css
- scripts/lib-franklin.js
Test URLs:
- After: https://paid-section--24petwatch--hlxsites.hlx.page/drafts/iakobchu/paid/membership
> #175 Add page www.24petwatch.com/paid/membership

- blocks/fragment-tabs/fragment-tabs.js
- scripts/scripts.js
Test URLs:
- Before: https://main--24petwatch--hlxsites.hlx.page/contact-us
- After: https://pm-448--24petwatch--hlxsites.hlx.page/contact-us
> #179 Add missing dataLayer calls PM-448

- blocks/pet-tag-quote/tag-quote.css
- blocks/pet-tag-quote/tag-select.css
Test URLs:
- Before: https://main--24petwatch--hlxsites.hlx.page/ca/lost-pet-protection/pet-tags/tag-quote
- After: https://pet-tags-styles-fix--24petwatch--hlxsites.hlx.page/ca/lost-pet-protection/pet-tags/tag-quote
> #181 Fix styles of pet-tags/tag-quote and pet-tags/tag-select

- blocks/footer/footer.js
- blocks/header/header.js
Test URLs:
- After: https://fix-navigation-links--24petwatch--hlxsites.hlx.page/
> Fix navigation links

- blocks/footer/footer.js
- blocks/header/header.js
- scripts/scripts.js
Test URLs:
- After: https://change-domain-update--24petwatch--hlxsites.hlx.page/
> hotfix for change domain

- blocks/footer-paid/footer-paid.js
- blocks/footer/footer.js
- blocks/header-paid/header-paid.js
- blocks/header/header.js
- scripts/lib-franklin.js
- scripts/scripts.js
Test URLs:
- After: https://menu-links-refactoring--24petwatch--hlxsites.hlx.page/
> Menu links refactoring

- blocks/footer-paid/footer-paid.js
- blocks/footer/footer.js
- blocks/header-paid/header-paid.js
- blocks/header/header.js
- scripts/lib-franklin.js
- scripts/scripts.js
* merge stage into main
* changed links decoration approach
Test URLs:
- After: https://stage--24petwatch--hlxsites.hlx.page/
> Menu links refactoring (#188)

- helix-sitemap.yaml
Test URLs:
- After: https://sitemap-path-fix--24petwatch--hlxsites.hlx.page/
> sitemap path fix

- blocks/plans-quote/form.js
- blocks/plans-quote/plans-quote.css
- blocks/thank-you/thank-you.js
Test URLs:
- Before: https://develop--24petwatch--hlxsites.hlx.page/lost-pet-protection/lpm-plus
- After: https://fix-owner-pet-issues--24petwatch--hlxsites.hlx.page/lost-pet-protection/lpm-plus
> Fixes for the form issues

- blocks/cards/cards.css
- blocks/header-paid/header-paid.css
- blocks/header-paid/header-paid.js
- blocks/membership-v2/membership-v2.css
- scripts/scripts.js
- styles/styles.css
Fix #[PM-467](https://pethealthinc.atlassian.net/browse/PM-467)
Test URLs:
- Before: https://main--24petwatch--hlxsites.hlx.page/paid/membership-v2
- After: https://feature-membership-v2-paid-page--24petwatch--hlxsites.hlx.page/paid/membership-v2
> 24PW: Membership V2 Paid Page - EDS Build

- blocks/cards/cards.css
- blocks/columns/columns.css
- blocks/header-paid/header-paid.css
- blocks/header-paid/header-paid.js
- blocks/lost-pet-protection/lost-pet-protection.css
- blocks/lost-pet-recovery/lost-pet-recovery.css
- blocks/membership-v2/membership-v2.css
- scripts/configs.js
- scripts/scripts.js
- styles/styles.css
Test URLs:
- Before: https://develop--24petwatch--hlxsites.hlx.page/
- After: https://stage--24petwatch--hlxsites.hlx.page/
> Backsync stage into develop

- blocks/pawpack/pawpack.css
- styles/styles.css
Fix #[PM-526](https://pethealthinc.atlassian.net/browse/PM-526)
Test URLs:
- Before: https://main--24petwatch--hlxsites.hlx.page/pawpack
- After: https://feature-pawpack-page--24petwatch--hlxsites.hlx.page/pawpack
> 24PW: Pawpack Page - EDS Build

- blocks/plans-quote/summary-quote.js
Test URLs:
- After: https://shipping-of-tag--24petwatch--hlxsites.hlx.page/
> Shipping of tag

- blocks/widget-aggregator/widget-aggregator.css
- blocks/widget-aggregator/widget-aggregator.js
This change is adding the aggregator widget / iframe block code currently used on petplace with changes to the ID's used for tracking purposes.
Fix #[PM-551](url)
Test URLs:
- Before: https://main--24petwatch--hlxsites.hlx.page/pet-insurance
- After: https://feature-pm-551-aggregator-widget--24petwatch--hlxsites.hlx.page/pet-insurance
> 24PW: Pet Insurance - Aggregator Widget

- blocks/thank-you/thank-you.js
- scripts/24petwatch-api.js
Fix # [PM-567](https://pethealthinc.atlassian.net/browse/PM-567)
Test URLs:
Before: https://main--24petwatch--hlxsites.hlx.page/thank-you?PaymentProcessorCustomerId=3cb80ce7-1e7b-41f5-bd24-f5716558fef0&flow=protectionfirst
After: https://dl-deploy-101524--24petwatch--hlxsites.hlx.page/thank-you?PaymentProcessorCustomerId=3cb80ce7-1e7b-41f5-bd24-f5716558fef0&flow=protectionfirst
> Merge changes from the feature/PM-56724-dl-thank-you into 'main' branch

- blocks/thank-you/thank-you.js
- scripts/24petwatch-utils.js
Adding currency to DL for the purchase event:
Fix #PM-618[<gh-issue-id>](https://pethealthinc.atlassian.net/browse/PM-618)
Test URLs:
Before: https://main--24petwatch--hlxsites.hlx.page/
After: https://feature-pm-618-dl-purchase-event--24petwatch--hlxsites.hlx.page/
> dataLayer updates: add currency to purchase event

- .github/pull_request_template.md
No Ticket
Update GitHub Pull Request Template
Add sections: 
- Jira Ticket 
- Purpose
- Changes
- Validate Changes
This markdown file can be previewed in VSCode (see screenshot below):
> GitHub pull request template update

- blocks/plans-quote/summary-quote.js
- scripts/24petwatch-utils.js
PM-564: https://pethealthinc.atlassian.net/browse/PM-564
PM-565: https://pethealthinc.atlassian.net/browse/PM-565
PM-566: https://pethealthinc.atlassian.net/browse/PM-566
Membership Cart (US and CA): Adding dataLayer events for the following:
1. View cart
2. Remove from cart
3. Begin checkout
- Added all 3 events logic in blocks/plans-quote/summary-quote.js
- Added sessionStorage item to store the last action initiated on summary if we need to use it to avoid triggering actions on page reload in scripts/24petwatch-utils.js
- Added object to store event names for use across cart
1. Pick an insurance product
2. Proceed to order summary page
- Check 'view_cart' event fires and check all DL items have been added
- Add some more products and check 'view_cart event fires again containing the …
> Sync to DEV: PM -564 Cart Summary DL events

- blocks/thank-you/thank-you.js
[PM-634](https://pethealthinc.atlassian.net/browse/PM-634)
CA Pet Tags - Fix issue where the user is unable to proceed to the the step 2 page after placing one order.
- After an order for tags is successfully placed, delete the pet tags cookie 
Please refer to the bug ticket above for testing criteria. 
- Before: https://main--24petwatch--hlxsites.hlx.page/ca/lost-pet-protection/pet-tags/tag-quote
- After: https://bugfix-pm-634-ca-pet-tags-order-issue--24petwatch--hlxsites.hlx.page/ca/lost-pet-protection/pet-tags/tag-quote
> Sync to Dev: Bugfix/pm 634 ca pet tags order issue

- blocks/plans-quote/form.js
- blocks/widget-aggregator/widget-aggregator.js
[PM-639](https://pethealthinc.atlassian.net/browse/PM-639)
[PM-572](https://pethealthinc.atlassian.net/browse/PM-572)
**PM-572:**
Update `source` prop to use the `source` variable.
**PM-639:**
Group all memberships purchased, in the ‘product type’ parameter (separated by commas).
- Add `productTypes` array to be used for `product_type` and `item_name`
- Remove `membershipName` variable and it's uses
**PM-572:**
- Open the Chrome Dev Tools 
- Search source code for the `source` prop's value listed in the sharepoint file for the aggregator widget.
**PM-639:**
With the Chrome Dev Tools console open and viewing the data layer events (via datalayer checker):
- Complete Step 1
- On Step 2, add a new pet, then select a membership plan, click the Add btn
- Confirm the add to cart DL event that is …
> Sync Release: Sprint 22 Fast Follow to Stage

- blocks/plans-quote/form.js
- blocks/widget-aggregator/widget-aggregator.js
[PM-637](https://pethealthinc.atlassian.net/browse/PM-637)
Remove hard-coded content where applicable so that it can be editable.
Correlate SharePoint content with the coded output.
- Before: https://main--24petwatch--hlxsites.hlx.page/ca/lost-pet-protection/pet-tags
- After: https://release-sprint-23-deploy--24petwatch--hlxsites.hlx.page/ca/lost-pet-protection/pet-tags
> Sync Sprint 23 deploy to Stage

- blocks/callout-get-a-quote/callout-get-a-quote.css
- blocks/default-block/default-block.css
- templates/paid-blog-page/paid-blog-page.css
[PM-694](https://pethealthinc.atlassian.net/browse/PM-694)
Address pages where the Block CSS and/or JS files are creating 404 errors. 
- 'callout get a quote': delete  dir / files 
- 'default block': add dir / files
- 'paid blog page': styling updates 
- 'pumpkin wellness club': add empty js file :(
Check the following urls and ensure there is no css / js files causing 404 errors in the dev tools console:
- Before: 
- https://main--24petwatch--hlxsites.hlx.page/archive/paid-blog-page
- https://main--24petwatch--hlxsites.hlx.page/pumpkin-wellness-club
- After: 
- https://bugfix-pm-694-broken-css-links--24petwatch--hlxsites.hlx.page/archive/paid-blog-page
- https://bugfix-pm-694-broken-css-links--24petwatch--hlxsites.hlx.page/pumpkin-wellness-club
> Sync to Sprint 23 Deploy: PM-694 Updates to address css/js 404s

- blocks/callout-get-a-quote/callout-get-a-quote.css
- blocks/default-block/default-block.css
- blocks/pet-tags/pet-tags.css
- blocks/pet-tags/pet-tags.js
- blocks/plans-quote/form.js
- blocks/plans-quote/plans-quote.css
- blocks/widget-aggregator/widget-aggregator.js
- templates/paid-blog-page/paid-blog-page.css
[PM-637](https://pethealthinc.atlassian.net/browse/PM-637)
[PM-652](https://pethealthinc.atlassian.net/browse/PM-652)
[PM-694](https://pethealthinc.atlassian.net/browse/PM-694)
**PM-637:**
- Remove hard-coded content where applicable so that it can be editable.
**PM-652:**
- Update CSS to fix elements overlapping on Step 1 of the Membership Form.
**PM-694:**
- 'callout get a quote': delete  dir / files 
- 'default block': add dir / files
- 'paid blog page': styling updates 
- 'pumpkin wellness club': add empty js file :(
**PM-637:**
Correlate SharePoint content with the coded output.
**PM-652:**
Observe the form label / inputs for the microchip number and promo code to ensure there is no overlap.
**PM-694:**
Check the following urls and ensure there is no css / js files causing 404 errors …
> Sync Release/Sprint 23 to Develop

- blocks/callout-get-a-quote/callout-get-a-quote.css
- blocks/default-block/default-block.css
- blocks/pet-tags/pet-tags.css
- blocks/pet-tags/pet-tags.js
- blocks/plans-quote/form.js
- blocks/plans-quote/plans-quote.css
- blocks/widget-aggregator/widget-aggregator.js
- templates/paid-blog-page/paid-blog-page.css
[PM-637](https://pethealthinc.atlassian.net/browse/PM-637)
[PM-652](https://pethealthinc.atlassian.net/browse/PM-652)
[PM-694](https://pethealthinc.atlassian.net/browse/PM-694)
**PM-637:**
- Remove hard-coded content where applicable so that it can be editable.
**PM-652:**
- Update CSS to fix elements overlapping on Step 1 of the Membership Form.
**PM-694:**
- 'callout get a quote': delete  dir / files 
- 'default block': add dir / files
- 'paid blog page': styling updates 
- 'pumpkin wellness club': add empty js file :(
**PM-637:**
Correlate SharePoint content with the coded output.
**PM-652:**
Observe the form label / inputs for the microchip number and promo code to ensure there is no overlap.
**PM-694:**
Check the following urls and ensure there is no css / js files causing 404 errors …
> Sync Release/Sprint 23 to Stage

- blocks/found-pet-report/found-pet-report.js
[PM-698](https://pethealthinc.atlassian.net/browse/PM-698)
**PM-698**
Update redirect logic to go to either US or CA thank you page.
**PM-698**
1. Go to the "Found Pet Report" page.
2. Complete and submit the form.
3. Observe the redirection behavior after submission.
- Before: https://main--24petwatch--hlxsites.hlx.page/lost-pet-protection/report-lost-found-pet#found-pet-report
- After: https://release-sprint-24-deploy--24petwatch--hlxsites.hlx.page/lost-pet-protection/report-lost-found-pet#found-pet-report
> Sync Sprint 24 Deploy to Main

- sitemap-index.xml
Adding a Sitemap index
Problem with organic traffic, would probably be solved with an update to the sitemap index.
> Adding sitemap index

- blocks/widget-aggregator/widget-aggregator.js
[PM-730](https://pethealthinc.atlassian.net/browse/PM-730)
- Removed extra conditionals
- Set up live url for widget
1. In order to test locally, update the aggregator widget by putting "dev-" before "quote" urls
2. View the 'pet-insurance' page, about half way down the page, confirm the aggregator widget is loading / functioning correctly
- After: https://feature-pm-730-agg-widget-update--24petwatch--hlxsites.hlx.page/
> Sync to Main: Feature PM-730 Aggregator Widget Update

- blocks/plans-quote/form.js
- scripts/scripts.js
[PM-796](https://pethealthinc.atlassian.net/browse/PM-796)
[PM-797](https://pethealthinc.atlassian.net/browse/PM-797)
[PM-268](https://pethealthinc.atlassian.net/browsePM-268)
- Before: https://main--24petwatch--hlxsites.hlx.page
- After: https://release-sprint-1-deploy--24petwatch--hlxsites.hlx.page
> Sync Sprint 1 Deploy to Main

- scripts/scripts.js
[PM-752](https://pethealthinc.atlassian.net/browse/PM-752)
- Update the url property 'scheme' to 'protocol' to update 'http' internal links to use 'https'
Please refer to the excel sheet in the jira ticket. Confirm that noted urls are no longer linking to an 'http' url but a 'https' url. 
- Before: https://release-sprint-1-deploy--24petwatch--hlxsites.hlx.page/
- After: https://feature-pm-752-internal-link-update--24petwatch--hlxsites.hlx.page
> Sync to Sprint 1 Deploy: PM-752 Update url formatting property

- helix-query.yaml
- robots.txt
[PM-756](https://pethealthinc.atlassian.net/browse/PM-756)
Resolving technical SEO task: Noindex Page in Sitemap
Updating the custom query index to exclude anything under /blog/experiments and exclude /blog/main-blog for blog_us 
- After: https://feature-pm-756-noindex-in-sitemap--24petwatch--hlxsites.hlx.page
> Sync to Stage: PM-756

- helix-query.yaml
- robots.txt
[PM-756](https://pethealthinc.atlassian.net/browse/PM-756)
Resolving technical SEO task: robots noindex page in sitemap
Updating the custom query index to exclude anything under /blog/experiments and exclude /blog/main-blog for blog_us 
- After: https://feature-pm-756-noindex-in-sitemap--24petwatch--hlxsites.hlx.page
> Sync to Main: PM-756

- blocks/cards/cards.js
- scripts/scripts.js
[PM-820](https://pethealthinc.atlassian.net/browse/PM-820)
[PM-752](https://pethealthinc.atlassian.net/browse/PM-752)
[PM-748](https://pethealthinc.atlassian.net/browse/PM-748)
See the following PR's for details of changes:
1. https://github.com/hlxsites/24petwatch/pull/314
2. https://github.com/hlxsites/24petwatch/pull/315
- Before: https://stage--24petwatch--hlxsites.hlx.page
- After: https://release-2025-sprint-2-deploy--24petwatch--hlxsites.hlx.page
> Sync to Stage: Sprint-2

- blocks/cards/cards.js
- scripts/scripts.js
[PM-820](https://pethealthinc.atlassian.net/browse/PM-820)
[PM-752](https://pethealthinc.atlassian.net/browse/PM-752)
[PM-748](https://pethealthinc.atlassian.net/browse/PM-748)
See the following PR's for details of changes:
1. https://github.com/hlxsites/24petwatch/pull/314
2. https://github.com/hlxsites/24petwatch/pull/315
See Jira task details for validation instructions
- After: https://release-2025-sprint-2-deploy--24petwatch--hlxsites.hlx.page
> Sync to main: Sprint 2

- blocks/found-pet-report/found-pet-report.js
- blocks/pet-tag-quote/tag-select.js
No ticket, quick fix
Updating coded phone numbers
Updating coded phone numbers from 1-866-597-2424 to 1-833-886-8002
- After: https://hotfix-update-phone-numbers--24petwatch--hlxsites.hlx.page/
> Hotfix, updating non editable phone numbers

- blocks/header-paid/header-paid.css
- blocks/header/header.css
- scripts/scripts.js
- styles/styles.css
https://pethealthinc.atlassian.net/browse/PM-937
A few issues were identified related to header, nav with promo banner.
See ticket for details:https://pethealthinc.atlassian.net/browse/PM-937
- After: https://hotfix-nav-with-promo--24petwatch--hlxsites.hlx.page/
> PM-937: Hotfix for header with promo

- blocks/accordion/accordion.css
- blocks/cards/cards.css
- blocks/columns/columns.css
- blocks/hero/hero.css
- styles/styles.css
https://phits.visualstudio.com/Marketing/_workitems/edit/98719
Styling changes on petwatch insurance landing page to match the figma design
Mainly css changes, some css classes were added to make sure the styles wouldn't affect other places, so I also did changes in the insurance docx by adding those classes
Changes can be validated in the page, following the comments from the ticket and comparing with the design: https://www.figma.com/design/XCjli7w3XjOfXNQa338TFs/24PetWatch---Website?node-id=1-4027&t=m4JAPnFtAmUAhO73-4
- After: https://feature-petwatch-page-updates--24petwatch--hlxsites.hlx.page/drafts/dayvson/pet-insurance
> 24PW: Insurance Landing Page - Updates

- blocks/plans-quote/plans-quote.css
- blocks/plans-quote/summary-quote.js
[PM-100497](https://phits.visualstudio.com/Marketing/_workitems/edit/100497)
Updating click to cancel copy on checkout flow for protection plan
Copy updates to LPM and Annual
Restyled plan summary parts to match the Figma design, updating margins and padding for both desktop and mobile viewports.
Ensure text and styling resembles the updates versions from the attached Figma file.
- Before:  https://release-sprint-9-deploy--24petwatch--hlxsites.hlx.page/
- After: https://feature-100497-ctc--24petwatch--hlxsites.hlx.page/
> Sync to release: 100497: Click-to-cancel

- blocks/plans-quote/plans-quote.css
- blocks/plans-quote/summary-quote.js
[PM-100497](https://phits.visualstudio.com/Marketing/_workitems/edit/100497)
Updating click to cancel copy on checkout flow for protection plans
Copy updates to LPM and Annual
Restyled plan summary parts to match the Figma design, updating margins and padding for both desktop and mobile viewports.
Validated by QA on release branch
- After: https://release-sprint-9-deploy--24petwatch--hlxsites.hlx.page/
> Sync to main: Sprint 9

- blocks/plans-quote/summary-quote.js
https://phits.visualstudio.com/Marketing/_boards/board/t/MarTech/Stories?workitem=101300
Updating click to cancel text on 24PW for LPM, LPM+ and Annual memberships
Changes validated by QA. Reference Azure ticket
/lost-pet-protection/summary-quote
- After: https://feature-101300-ctc-copy-updates--24petwatch--hlxsites.hlx.page/
> Deploy to main: 101300

- head.html
[102843](https://phits.visualstudio.com/Marketing/_boards/board/t/Customer%20Experience/Stories?workitem=102843)
As per our privacy policy compliancy, we need to configure Osano.js script into our site header for 24petwatch.com. 
Adding osano script to head.html
Script: <script src="https://cmp.osano.com/AzZnQYUKjmniQ4Zwf/11178055-b830-4f16-a243-92e4e98bb74b/osano.js"></script>
- After: https://feature-102843-osano--24petwatch--hlxsites.hlx.page/
> 102843: Adding Osano script
