hlxsites/24petwatch

- blocks/plans-quote/form.js
Fix N/A
Test URLs:
- After: https://promocode-old-format--24petwatch--hlxsites.hlx.page/
> Added suppor the new API response format and the old response format for the PROMO code validator

- blocks/header/header.js
Please always provide the [GitHub issue(s)](https://github.com/hlxsites/24petwatch/issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #[PM-467](https://pethealthinc.atlassian.net/browse/PM-467)
Bug Fixes: Call toggleMenu on membership in-page anchor links to close open mobile menu
Test URLs:
Before: https://main--24petwatch--hlxsites.hlx.page/lost-pet-protection/membership
After: https://bugfix-mobile-nav-redirect-visibility--24petwatch--hlxsites.hlx.page/lost-pet-protection/membership
> Mobile - Navigation menu stays open after redirect on membership page

- scripts/lib-franklin.js
- templates/paid-blog-page/paid-blog-page.css
Fix: 
- Revert `decorateButtons` to previous version (prior to porting over Petplace code) 
- Add styling for the Callout ctas on the Paid Blog Page 
Test URLs:
- After: https://bugfix-decorate-buttons--24petwatch--hlxsites.hlx.page/paid-blog-page
https://bugfix-decorate-buttons--24petwatch--hlxsites.hlx.page/lost-pet-protection/membership
> Revert decorateButtons function, apply callout cta styling

- blocks/header-paid/header-paid.js
Added 2 new fragments for header:
- fragments > us> header-paid-blog
- fragments >  ca > header-paid-blog
The new header fragment will be used on any page using Template : paid-blog-page 
“Get Started” CTA on the paid blog template should go to: /lost-pet-protection/membership
“Get Started” CTA on the paid pages should go to: /lost-pet-protection/lps-quote
paid page: https://feature-pm-556-paid-blog-header--24petwatch--hlxsites.hlx.page/paid/membership
Paid blog page: https://feature-pm-556-paid-blog-header--24petwatch--hlxsites.hlx.page/paid-blog-page
Fix #[<gh-issue-id>](https://pethealthinc.atlassian.net/browse/PM-556)
Test URLs:
- Before: https://main--24petwatch--hlxsites.hlx.page/paid-blog-page
- After: https://feature-pm-556-paid-blog-header--24petwatch--hlxsites.hlx.page/paid-blog- …
> Added condition to load paid blog header fragment for paid blog template

- blocks/thank-you/thank-you.js
This change requires the existing data in DL to be wrapped inside an 'ecommerce' object on the thank you page
[Fix #<gh-issue-id>](https://pethealthinc.atlassian.net/browse/PM-618)
Test URLs:
Before: https://main--24petwatch--hlxsites.hlx.page/
After: https://feature-pm-618-dl-purchase-event--24petwatch--hlxsites.hlx.page/
> dataLayer updates: wrap tracking data inside ecommerce object

- blocks/header-paid/header-paid.js
Added 2 new fragments for header:
fragments > us> header-paid-blog
fragments > ca > header-paid-blog
The new header fragment will be used on any page using Template : paid-blog-page
“Get Started” CTA on the paid blog template should go to: /lost-pet-protection/membership
“Get Started” CTA on the paid pages should go to: /lost-pet-protection/lps-quote
paid page: https://feature-pm-556-paid-blog-header--24petwatch--hlxsites.hlx.page/paid/membership
Paid blog page: https://feature-pm-556-paid-blog-header--24petwatch--hlxsites.hlx.page/paid-blog-page
Fix #[PM-556](https://pethealthinc.atlassian.net/browse/PM-556)
Test URLs:
Before: https://release-sprint-22-deploy--24petwatch--hlxsites.hlx.page/paid-blog-page
After: https://feature-pm-556-paid-blog-header--24petwatch--hlxsites.hlx.page/paid-bl …
> Sync to sprint deploy: Added condition to load paid blog header fragment on paid blog template

- blocks/thank-you/thank-you.js
- scripts/24petwatch-utils.js
[PM-618](https://pethealthinc.atlassian.net/browse/PM-618)
Membership Cart (US and CA): On a completed order, update DL with order details
Updating existing DL with new requirements, adding items array containing each pet membership
Complete and order, in Dev Tools open and view the data layer to validate all data exists as set out in the [ticket](https://pethealthinc.atlassian.net/browse/PM-618)
Before: https://develop--24petwatch--hlxsites.hlx.page/thank-you
After: https://feature-pm-618-dl-modifications--24petwatch--hlxsites.hlx.page/thank-you
> Sync to DEV: Updating purchase event DL with new requirements

- blocks/plans-quote/form.js
[PM-639](https://pethealthinc.atlassian.net/browse/PM-639)
Group all memberships purchased, in the ‘product type’ parameter (separated by commas).
- Add `productTypes` array to be used for `product_type` and `item_name`
- Remove `membershipName` variable and it's uses
With the Chrome Dev Tools console open and viewing the data layer events (via datalayer checker):
- Complete Step 1
- On Step 2, add a new pet, then select a membership plan, click the Add btn
- Confirm the add to cart DL event that is being sent includes the parent `product_type` property contains multiple membership values that are comma separated.  
----
- Before: https://release-sprint-22-fast-follow--24petwatch--hlxsites.hlx.page/lost-pet-protection/lps-quote
- After: …
> Sync to Release/Sprint 22 Fast Follow: PM-639 Update 'add to cart' DL product type values

- blocks/plans-quote/form.js
[PM-639](https://pethealthinc.atlassian.net/browse/PM-639)
Group all memberships purchased, in the ‘product type’ parameter (separated by commas).
- Add `productTypes` array to be used for `product_type` and `item_name`
- Remove `membershipName` variable and it's uses
With the Chrome Dev Tools console open and viewing the data layer events (via datalayer checker):
- Complete Step 1
- On Step 2, add a new pet, then select a membership plan, click the Add btn
- Confirm the add to cart DL event that is being sent includes the parent `product_type` property contains multiple membership values that are comma separated.  
----
- Before: https://develop--24petwatch--hlxsites.hlx.page/lost-pet-protection/lps-quote
- After: https://release-sprint-22-fast-follow--24petwatch--hlxsites.hlx.page/lost-p …
> Sync Release/Sprint 22 Fast Follow to develop

- blocks/plans-quote/form.js
- blocks/widget-aggregator/widget-aggregator.js
[PM-639](https://pethealthinc.atlassian.net/browse/PM-639)
[PM-572](https://pethealthinc.atlassian.net/browse/PM-572)
**PM-572:**
Update `source` prop to use the `source` variable.
**PM-639:**
Group all memberships purchased, in the ‘product type’ parameter (separated by commas).
- Add `productTypes` array to be used for `product_type` and `item_name`
- Remove `membershipName` variable and it's uses
**PM-572:**
- Open the Chrome Dev Tools 
- Search source code for the `source` prop's value listed in the sharepoint file for the aggregator widget.
**PM-639:**
With the Chrome Dev Tools console open and viewing the data layer events (via datalayer checker):
- Complete Step 1
- On Step 2, add a new pet, then select a membership plan, click the Add btn
- Confirm the add to cart DL event that is …
> Prod Release: Sprint 22 Fast Follow to Main

- blocks/plans-quote/form.js
- blocks/plans-quote/plans-quote.css
[PM-652](https://pethealthinc.atlassian.net/browse/PM-652)
Update CSS to fix elements overlapping on Step 1 of the Membership Form.
Observe the form label / inputs for the microchip number and promo code to ensure there is no overlap. 
- Before: https://main--24petwatch--hlxsites.hlx.page/lost-pet-protection/lps-quote
- After: https://bugfix-pm-652-cart-ui-overlap--24petwatch--hlxsites.hlx.page/lost-pet-protection/lps-quote
> Sync to Sprint Deploy 23: PM-652 Cart UI Overlap Issues

- blocks/found-pet-report/found-pet-report.js
[PM-698](https://pethealthinc.atlassian.net/browse/PM-698)
Update redirect logic to go to either US or CA thank you page.
1. Go to the "Found Pet Report" page.
2. Complete and submit the form.
3. Observe the redirection behavior after submission.
- Before: https://main--24petwatch--hlxsites.hlx.page/lost-pet-protection/report-lost-found-pet#found-pet-report
- After: https://aem-stage.24petwatch.com/lost-pet-protection/report-lost-found-pet#found-pet-report
> Sync to Stage: Bugfix PM-698 CA Found Pet Report Redirect

- blocks/found-pet-report/found-pet-report.js
[PM-698](https://pethealthinc.atlassian.net/browse/PM-698)
Update redirect logic to go to either US or CA thank you page.
1. Go to the "Found Pet Report" page.
2. Complete and submit the form.
3. Observe the redirection behavior after submission.
- Before: https://release-sprint-24-deploy--24petwatch--hlxsites.hlx.page/lost-pet-protection/report-lost-found-pet#found-pet-report
- After: https://aem-stage.24petwatch.com/lost-pet-protection/report-lost-found-pet#found-pet-report
> Sync to Sprint 24 Deploy: PM-698 CA Found Pet Report Redirect

- blocks/plans-quote/costco-promo.js
- blocks/plans-quote/form.js
- blocks/plans-quote/plans-quote.css
- blocks/plans-quote/summary-quote.js
- blocks/thank-you/thank-you.js
- scripts/24petwatch-api.js
- scripts/24petwatch-utils.js
[PM-375](https://pethealthinc.atlassian.net/browse/PM-375)
Under the epic PM-375 these changes are for all tasks related to the FE flow for a Costco Figo promotion
See all tasks under https://pethealthinc.atlassian.net/browse/PM-375
1. Get poid (policy Id) from query string if page path is PET_PLANS_ANNUAL_URL (/annual-quote)
2. Validate the policy Id exists is Salesforce records and is eligible for promo based on eligibility criteria (via new proxy service)
3. If valid, request promo from assignNextAvailableCoupon API
4. IF a valid promo is returned, add to promo field and disable input
5. IF multipet is false, on summary flow remove add a pet option and don't persist cart on return after abandoned cart
See all validation requirements on each task under epic: …
> PM-375: Costco Figo Promotion (#283)

- blocks/plans-quote/costco-promo.js
- blocks/plans-quote/form.js
- blocks/plans-quote/plans-quote.css
- blocks/plans-quote/summary-quote.js
- blocks/thank-you/thank-you.js
- scripts/24petwatch-api.js
- scripts/24petwatch-utils.js
[PM-375](https://pethealthinc.atlassian.net/browse/PM-375)
Under the epic PM-375 these changes are for all tasks related to the FE flow for a Costco Figo promotion
See all tasks under https://pethealthinc.atlassian.net/browse/PM-375
1. Get poid (policy Id) from query string if page path is PET_PLANS_ANNUAL_URL (/annual-quote)
2. Validate the policy Id exists is Salesforce records and is eligible for promo based on eligibility criteria (via new proxy service)
3. If valid, request promo from assignNextAvailableCoupon API
4. IF a valid promo is returned, add to promo field and disable input
5. IF multipet is false, on summary flow remove add a pet option and don't persist cart on return after abandoned cart
See all validation requirements on each task under epic: …
> PM-375: Costco Figo Promotion: Sync to Stage

- scripts/scripts.js
Feature: https://pethealthinc.atlassian.net/browse/PM-268
cta_click event is missing the cta_location parameter in some cases
The dataLayer now includes the name and index of the container block in the cta_location parameter for the cta_click event 
1. Go to: https://feature-pm-268-cta-location--24petwatch--hlxsites.hlx.page/
2. Inspect any element or [open the developer tools](https://developer.chrome.com/docs/devtools/open/)
3. Go to the Network tab
4. Check The Preserve the logs checkbox ✅
5. Enable the Filters and filter by Fetch/XHR
6. Clear the Network Log 🚫
7. Now click on any cta on the page 🖱️
9. Select the first collect? request
10. Look up for the ep.cta_location under the Payload tab
- After: …
> Enhance CTA tracking by identifying block names and their indices

- blocks/plans-quote/form.js
[PM-797](https://pethealthinc.atlassian.net/browse/PM-797)
Currently there’s a cookie being stored on Step 1 of the webcarts. Meaning if a customer abandons a cart, and comes back later to try again, the user info is stored and they no longer can proceed to Step 1. To improve the customer experience on our webcarts, we’re going to remove the cookie on Step 1, as it is only relevant for Step 2. 
We are deleting the savedOwnerID cookie when a user returns to the membership flow for the first form step. We do not delete the cookie if the user is editing petInfo from step 1.
See https://pethealthinc.atlassian.net/browse/PM-797 for testing criteria
> Sync to release: PM-797

- blocks/header/header.js
- scripts/scripts.js
[PM-806](https://pethealthinc.atlassian.net/browse/PM-806)
On some CTA clicks triggering the trackGTMEvent, we are missing the cta_location in DataLayer.
There is some custom logic set up in instrumentTrackingEvents() which is not setting the cta_location, due to some CTA's being authored outside of blocks.
- As a fallback, we are now going to capture the closest section as the location when the CTA has not met any of the existing conditionals.
- The header is missing cta_location, this has been added in.
Review https://pethealthinc.atlassian.net/browse/PM-806 for validation steps.
Before: https://stage--24petwatch--hlxsites.hlx.page
After: https://feature-pm-806-cta-click-dl--24petwatch--hlxsites.hlx.page/
> Sync to Stage: PM-806: Add DL fallback for cta_locations

- blocks/header/header.js
- scripts/scripts.js
[PM-806](https://pethealthinc.atlassian.net/browse/PM-806)
On some CTA clicks triggering the trackGTMEvent, we are missing the cta_location in DataLayer.
There is some custom logic set up in instrumentTrackingEvents() which is not setting the cta_location, due to some CTA's being authored outside of blocks.
- As a fallback, we are now going to capture the closest section as the location when the CTA has not met any of the existing conditionals.
- The header is missing cta_location, this has been added in.
Review https://pethealthinc.atlassian.net/browse/PM-806 for validation steps.
Before: https://stage--24petwatch--hlxsites.hlx.page
After: https://feature-pm-806-cta-click-dl--24petwatch--hlxsites.hlx.page/
> Sync to Stage: PM-806: Add default Pumpkin Wellness cta_location for DL

- blocks/header/header.js
- scripts/scripts.js
[PM-806](https://pethealthinc.atlassian.net/browse/PM-806)
On some CTA clicks triggering the trackGTMEvent, we are missing the cta_location in DataLayer.
There is some custom logic set up in instrumentTrackingEvents() which is not setting the cta_location, due to some CTA's being authored outside of blocks.
- As a fallback, we are now going to capture the closest section as the location when the CTA has not met any of the existing conditionals.
- The header is missing cta_location, this has been added in.
Review https://pethealthinc.atlassian.net/browse/PM-806 for validation steps.
- Before: https://main--24petwatch--hlxsites.hlx.page
- After: https://feature-pm-806-cta-click-dl--24petwatch--hlxsites.hlx.page
> Deploy to main: PM-806: Add DL fallback for cta_locations

- blocks/cards/cards.js
[PM-820](https://pethealthinc.atlassian.net/browse/PM-820)
A bug exists on the card block, where if an link doesn't exist, the block code ads an undefined href value on an anchor wrapped around a heading. This link results in a 404.
We are resolving this with a check on href before setting the anchor on a heading:
- Add nullish check on href value before setting anchor on card header
1. Scroll down the page to a cards section, where the cards have headings: Step 1 - Step 5. 
2. The heading should no longer contain an anchor, resolving the issue of linking to a 404 page.
- Before: https://main--24petwatch--hlxsites.hlx.page/lost-pet-protection/pet-recovery-tips
- After: https://feature-pm-820-card-block--24petwatch--hlxsites.hlx.page/lost-pet-protection/pet-recovery-tips
> PM-820: add nullish check on anchor for card heading

- plugins/rum-conversion/.eslintrc.js
- scripts/scripts.js
[PM-752](https://pethealthinc.atlassian.net/browse/PM-752)
[PM-748](https://pethealthinc.atlassian.net/browse/PM-748)
Technical SEO resolution fixing broken links, 404s and indexable pages linking to http protocol
To fix this, we are updating the method cleanLocalhostLinks to set the protocol, hostname and port of converted localhost links from the SharePoint docs to the existing window properties.
This enforces that the converted links are set using the current environment properties.
See https://pethealthinc.atlassian.net/browse/PM-748 for validation instruction.
- Before: https://main--24petwatch--hlxsites.hlx.page
- After: https://feature-pm-752-internal-link-update--24petwatch--hlxsites.hlx.page
> PM-752: Fixes for HTTPS has Internal Links to HTTP

- blocks/cards/cards.css
This is a hotfix for an issue identified with cards on the insurance page.
On the section class (pumpkin wellness) we are unsetting the aspect ratio for the cards img.
changes have been validated by QA with regression against all card block variations.
Before: 
After:
- Before: https://main--24petwatch--hlxsites.hlx.page/lost-pet-protection
- After: https://hotfix-cards-aspect-ratio--24petwatch--hlxsites.hlx.page/lost-pet-protection
> Deploy to main: Hotfix for cards aspect ratio

- blocks/plans-quote/summary-quote.js
[PM-101800](https://phits.visualstudio.com/Marketing/_workitems/edit/101800)
Adding new logic related to click to cancel:
- Unchecking opt-in checkboxes by default
- Disabled the proceed to payment button until all opt-in's are checked
By default, the product opt-in checkboxes on the plan summary step have been changed to unchecked by removing a condition.
Adding a method to check all product opt in checkboxes and determine if the 'proceed to payment' button should be enabled or disabled. 
This method will execute on load and in the event handler when checking / unchecking opt-ins
Changes have been validated by QA, refer to ticker: https://phits.visualstudio.com/Marketing/_workitems/edit/101800
To follow validation steps, select any membership product > proceed to step 2 > 'proceed to …
> Deploy to main: 101800

- blocks/columns/columns.css
- blocks/plans-quote/plans-quote.css
- blocks/plans-quote/summary-quote.js
- scripts/24petwatch-api.js
- scripts/24petwatch-utils.js
[1353](https://dev.azure.com/PetPlaceProduct/24Pet/_workitems/edit/1353)
[1466](https://dev.azure.com/PetPlaceProduct/24Pet/_workitems/edit/1466)
Click to cancel updates
- Required a new auto renew checkbox for PWC and copy updates
- By default, auto renew checkboxes have changes to checked state
- Remember pet autoRenew selections on page refresh (happens when adding new pet)
- PWC required updated API changes with a optional param in payload of the PWC item id
**Fully tested with BE and QA signed off.**
- Before: https://stage--24petwatch--hlxsites.hlx.page/
- After: https://feature-1353-ctc-updates--24petwatch--hlxsites.hlx.page/
> feat: Add logic and styling for new PWC  autoRenew options

- blocks/columns/columns.css
- blocks/plans-quote-perks-decorator/plans-quote-perks-decorator.css
- blocks/plans-quote/plans-quote.css
- blocks/plans-quote/summary-quote.js
- scripts/24petwatch-api.js
- scripts/24petwatch-utils.js
[1353](https://dev.azure.com/PetPlaceProduct/24Pet/_workitems/edit/1353)
[1466](https://dev.azure.com/PetPlaceProduct/24Pet/_workitems/edit/1466)
Click to cancel updates
- Required a new auto renew checkbox for PWC and copy updates
- By default, auto renew checkboxes have changes to checked state
- Remember pet autoRenew selections on page refresh (happens when adding new pet)
- PWC required updated API changes with a optional param in payload of the PWC item id
**Fully tested with BE and QA signed off.**
- Before: https://stage--24petwatch--hlxsites.hlx.page/
- After: https://feature-1353-ctc-updates--24petwatch--hlxsites.hlx.page/
> feat: Add logic and styling for new PWC auto renew options - 1353
